using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms; 
using System.Data.SqlClient;

namespace takip
{
    public partial class goster : Form
    {
        public goster()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
        }
        private void goster_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'takipDataSet12.musteri' table. You can move, or remove it, as needed.
            this.musteriTableAdapter.Fill(this.takipDataSet12.musteri);
            gridView1.BestFitColumns();
            this.gridView1.OptionsView.ShowFooter = true;
            this.gridView1.OptionsBehavior.Editable = true;
        }

        private void bunifuMaterialTextbox1_Enter(object sender, EventArgs e)
        {
        }

        private void bunifuMaterialTextbox1_Leave(object sender, EventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
